---
ID: "9d241b5c-92cc-4c04-94aa-5ee17cc0516c"
Parent: "c7d9d293-4ef8-4380-8e10-c4632e729f39"
Template: "c7d9d293-4ef8-4380-8e10-c4632e729f39"
Path: /sitecore/templates/Project/Common/Content Types/Teasers/Teaser/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160511T130000Z
