---
ID: 511b6c4f-3a50-4825-b377-f334f3dfc06c
Parent: 193d6783-7fee-4e4c-80d8-43ad0ec11bdd
Template: ab86861a-6030-46c5-b394-e8f99e8b87db
Path: /sitecore/templates/Feature/Demo Tools/Demo Tools Settings
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160303T102204Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
